import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Menu} from '@components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin Zuhot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container flex flex-row'>
          <Menu />
          <div className='mx-2' style={{width: "85%"}}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
